#!/usr/bin/env bash
# infra/scripts/deploy.sh: deploy PitchBend Live at a given git SHA (ARCHITECTURE.md §9 task 11).
#
# THIS IS A PRODUCTION DEPLOY. The pitchbend-live namespace on the Oracle VM is the
# only environment; there is no staging (CLAUDE.md §5). Deploys are manual:
# never run this from CI (no cluster credentials in CI, ever).
#
# Usage:  infra/scripts/deploy.sh [--yes] <git-sha>
#   <git-sha>   7-40 hex chars: the tag CI pushed to GHCR for BOTH images
#   --yes, -y   skip the interactive confirmation
# Env:    ROLLOUT_TIMEOUT  per-Deployment rollout wait (default 600s)
# Needs:  bash 3.2+ (the macOS default works), kubectl (built-in kustomize), curl
#
# What it does, in order (everything that can fail offline runs before the prompt):
#   1. Validate the SHA and render a temporary kustomize overlay (mktemp -d) over
#      a snapshot copy of infra/k8s that sets both image tags to the SHA. The
#      committed kustomization.yaml is never modified. This replaces §9's
#      `kustomize edit set image`, so no separate kustomize binary is needed.
#   2. Refuse to continue if the render contains a Secret (it would overwrite
#      the real pitchbend-live-secrets) or any PitchBend Live image isn't pinned to the SHA.
#   3. Check that both images exist on GHCR, are anonymously pullable (public),
#      and include linux/arm64.
#   4. Show the kubectl context and ask for confirmation (unless --yes). Every
#      later kubectl call is pinned to that context.
#   5. Create the namespace if it's missing; stop if Secret pitchbend-live-secrets is missing.
#   6. Apply exactly the render validated in step 2, then wait for each Deployment.
set -euo pipefail

readonly NAMESPACE=pitchbend-live
readonly SECRET=pitchbend-live-secrets
readonly REGISTRY=ghcr.io
readonly OWNER=edwinargueta
readonly IMAGE_REPOS="pitchbend-live-api pitchbend-live-web"
readonly ROLLOUT_TIMEOUT="${ROLLOUT_TIMEOUT:-600s}"
readonly MANIFEST_ACCEPT='application/vnd.oci.image.index.v1+json,application/vnd.docker.distribution.manifest.list.v2+json,application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.manifest.v2+json'

log() { printf '==> %s\n' "$*"; }
die() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}
usage() {
  sed -n 's/^# \{0,1\}//; /^Usage:/,/^Needs:/p' "$0"
}

# write_overlay DIR BASE_DIR SHA
# Copies BASE_DIR (infra/k8s) to DIR/base and writes DIR/kustomization.yaml, an
# overlay of ./base that sets both PitchBend Live image tags to SHA.
# Why a copy: kustomize rejects absolute paths in `resources:` ("new root
# cannot be absolute"), and a relative path out of $TMPDIR is fragile (on macOS
# /var is a symlink to /private/var). A snapshot also means what gets applied
# can't change while the confirmation prompt waits.
# The SHA is YAML-quoted so e.g. 1234567 or 12e4567 stays a string, not a number.
write_overlay() {
  local dir=$1 base=$2 sha=$3 repo
  cp -R "$base" "$dir/base"
  {
    echo "# Temporary overlay generated by infra/scripts/deploy.sh; deleted on exit."
    echo "apiVersion: kustomize.config.k8s.io/v1beta1"
    echo "kind: Kustomization"
    echo "resources:"
    echo "  - base"
    echo "images:"
    for repo in $IMAGE_REPOS; do
      echo "  - name: $REGISTRY/$OWNER/$repo"
      echo "    newTag: '$sha'"
    done
  } >"$dir/kustomization.yaml"
}

# check_ghcr_image OWNER REPO TAG
# Succeeds if ghcr.io/OWNER/REPO:TAG exists, can be pulled anonymously (so the
# package is public, which the cluster needs because it has no pull secret),
# and includes linux/arm64. Uses curl only.
check_ghcr_image() {
  local owner=$1 repo=$2 tag=$3 nl=$'\n'
  local ref="$REGISTRY/$owner/$repo:$tag" token_resp token_status token resp status body flat digest cfg
  local private_hint="New GHCR packages are PRIVATE by default: on GitHub open Packages -> $repo -> Package settings -> Change visibility -> Public. (If it was never pushed, check that CI's image workflow ran.)"

  token_resp=$(curl -sS --max-time 20 -w "$nl%{http_code}" \
    "https://$REGISTRY/token?scope=repository:$owner/$repo:pull&service=$REGISTRY" 2>&1) || {
    echo "  $ref: could not reach $REGISTRY: ${token_resp%%"$nl"*}" >&2
    return 1
  }
  token_status=${token_resp##*"$nl"}
  token=$(sed -n 's/.*"token"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' <<<"${token_resp%"$nl"*}")
  if [[ "$token_status" != 200 || -z "$token" ]]; then
    echo "  $ref: no anonymous pull access (token HTTP $token_status). The package is private or doesn't exist." >&2
    echo "     $private_hint" >&2
    return 1
  fi

  resp=$(curl -sS --max-time 30 -w "$nl%{http_code}" \
    -H "Authorization: Bearer $token" -H "Accept: $MANIFEST_ACCEPT" \
    "https://$REGISTRY/v2/$owner/$repo/manifests/$tag" 2>&1) || {
    echo "  $ref: manifest request failed: ${resp%%"$nl"*}" >&2
    return 1
  }
  status=${resp##*"$nl"}
  body=${resp%"$nl"*}
  case "$status" in
    200) ;;
    401 | 403)
      echo "  $ref: not anonymously pullable (HTTP $status)." >&2
      echo "     $private_hint" >&2
      return 1
      ;;
    404)
      echo "  $ref: tag not found (HTTP 404). Has CI finished pushing this SHA? Pass exactly the tag CI pushed." >&2
      return 1
      ;;
    *)
      echo "  $ref: unexpected HTTP $status from $REGISTRY" >&2
      return 1
      ;;
  esac

  flat=$(tr -d '[:space:]' <<<"$body")
  if [[ "$flat" != *'"manifests":['* ]]; then
    # Single-platform manifest: the architecture is in its config blob.
    digest=$(sed -n 's/.*"config":{[^}]*"digest":"\(sha256:[0-9a-f]\{64\}\)".*/\1/p' <<<"$flat")
    cfg=""
    if [[ -n "$digest" ]]; then
      cfg=$(curl -fsSL --max-time 30 -H "Authorization: Bearer $token" \
        "https://$REGISTRY/v2/$owner/$repo/blobs/$digest" 2>/dev/null) || cfg=""
    fi
    flat=$(tr -d '[:space:]' <<<"$cfg")
  fi
  if [[ "$flat" != *'"architecture":"arm64"'* ]]; then
    echo "  $ref: exists and is public, but has no linux/arm64 image (the VM is arm64 only, CLAUDE.md §1)." >&2
    return 1
  fi
  echo "  $ref: OK (public, linux/arm64)"
}

# Pinned to the context the user confirmed, so a context switch in another
# terminal can't redirect the rest of the deploy.
kc() { kubectl --context "$CONTEXT" "$@"; }

print_secret_instructions() {
  cat >&2 <<'EOF'

Secret pitchbend-live-secrets is missing. Create it once per cluster, then re-run deploy.sh.
Paste these into a bash shell (in zsh, run `bash` first: zsh's `read -p` means
something else). The values never appear on a command line, in `ps`, or in shell history:

  read -rsp 'DUCKDNS_TOKEN: ' DUCKDNS_TOKEN; echo
  read -rsp 'SENTRY_DSN (Enter for none): ' SENTRY_DSN; echo
  kubectl -n pitchbend-live create secret generic pitchbend-live-secrets \
    --from-file=DUCKDNS_TOKEN=<(printf '%s' "$DUCKDNS_TOKEN") \
    --from-file=SENTRY_DSN=<(printf '%s' "$SENTRY_DSN")
  unset DUCKDNS_TOKEN SENTRY_DSN

Never commit it, and never put it in a file under the repo (CLAUDE.md §2).
EOF
}

main() {
  local yes=0 sha="" arg
  for arg in "$@"; do
    case "$arg" in
      -y | --yes) yes=1 ;;
      -h | --help)
        usage
        exit 0
        ;;
      -*) die "unknown option: $arg (see --help)" ;;
      *)
        [[ -z "$sha" ]] || die "expected exactly one <git-sha> (see --help)"
        sha=$arg
        ;;
    esac
  done
  [[ -n "$sha" ]] || {
    usage >&2
    exit 2
  }
  local sha_re='^[0-9a-f]{7,40}$'
  sha=$(tr 'A-F' 'a-f' <<<"$sha")
  [[ "$sha" =~ $sha_re ]] || die "'$sha' is not a git SHA (7-40 hex characters)"

  command -v kubectl >/dev/null 2>&1 || die "kubectl is not on PATH"
  command -v curl >/dev/null 2>&1 || die "curl is not on PATH"

  local script_dir k8s_dir
  script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
  k8s_dir="$(cd -- "$script_dir/../k8s" && pwd)"
  [[ -f "$k8s_dir/kustomization.yaml" ]] || die "no kustomization.yaml in $k8s_dir"

  # --- 1. Temporary overlay + offline render ---------------------------------
  local tmp_base="${TMPDIR:-/tmp}"
  TMP_DIR=$(mktemp -d "${tmp_base%/}/pitchbend-live-deploy.XXXXXX")
  trap 'rm -rf -- "$TMP_DIR"' EXIT
  write_overlay "$TMP_DIR" "$k8s_dir" "$sha"
  log "Rendering infra/k8s with image tag $sha (client-side, no cluster access)"
  kubectl kustomize "$TMP_DIR" >"$TMP_DIR/rendered.yaml" || die "kustomize render failed"

  # --- 2. Safety checks on the render ----------------------------------------
  if grep -qE '^kind:[[:space:]]*Secret[[:space:]]*$' "$TMP_DIR/rendered.yaml"; then
    die "the render contains a Secret. Is secret.example.yaml listed in kustomization.yaml? Refusing: applying it would overwrite the real $SECRET."
  fi
  if grep -q 'set-by-deploy-sh' "$TMP_DIR/rendered.yaml"; then
    die "an image still has the placeholder tag after the overlay; check the images: block"
  fi
  local repo
  for repo in $IMAGE_REPOS; do
    grep -qF "image: $REGISTRY/$OWNER/$repo:$sha" "$TMP_DIR/rendered.yaml" ||
      die "rendered manifests don't use $REGISTRY/$OWNER/$repo:$sha"
  done
  # Every image must carry an explicit tag (or digest) that isn't latest.
  local img last unpinned=""
  while IFS= read -r img; do
    last=${img##*/}
    if [[ "$last" != *[:@]* || "$last" == *:latest ]]; then unpinned+=" $img"; fi
  done < <(sed -n 's/^[[:space:]-]*image:[[:space:]]*//p' "$TMP_DIR/rendered.yaml" | tr -d "\"'")
  [[ -z "$unpinned" ]] || die "unpinned image(s), untagged or :latest:$unpinned (CLAUDE.md §8)"

  # --- 3. Images exist, are public, and are arm64 ----------------------------
  log "Checking images on $REGISTRY (anonymous, like the cluster)"
  local images_ok=1
  for repo in $IMAGE_REPOS; do
    check_ghcr_image "$OWNER" "$repo" "$sha" || images_ok=0
  done
  ((images_ok)) || die "image check failed (see above); nothing was applied"

  # --- 4. Confirm the target -------------------------------------------------
  CONTEXT=$(kubectl config current-context 2>/dev/null) || die "no current kubectl context is set"
  local server
  server=$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}' 2>/dev/null) || server="?"
  printf '\n  PRODUCTION DEPLOY (there is no staging)\n'
  printf '  context:   %s\n  server:    %s\n  namespace: %s\n  images:    %s\n\n' \
    "$CONTEXT" "$server" "$NAMESPACE" "$REGISTRY/$OWNER/{pitchbend-live-api,pitchbend-live-web}:$sha"
  if ((!yes)); then
    [[ -t 0 ]] || die "stdin is not a terminal; re-run with --yes to confirm non-interactively"
    local answer=""
    read -r -p "Type y to deploy: " answer || answer=""
    [[ "$answer" == y ]] || die "aborted; nothing was applied"
  fi

  # --- 5. Namespace and Secret -----------------------------------------------
  local out
  if ! out=$(kc get namespace "$NAMESPACE" -o name 2>&1); then
    grep -q NotFound <<<"$out" || die "could not check namespace $NAMESPACE: $out"
    log "Creating namespace $NAMESPACE"
    kc apply -f "$TMP_DIR/base/namespace.yaml"
  fi
  if ! out=$(kc -n "$NAMESPACE" get secret "$SECRET" -o name 2>&1); then
    grep -q NotFound <<<"$out" || die "could not check Secret $SECRET: $out"
    print_secret_instructions
    exit 1
  fi

  # --- 6. Apply and wait -----------------------------------------------------
  # Apply the exact bytes validated above (equivalent to `kubectl apply -k`
  # on the overlay, minus the chance of files changing during the prompt).
  log "Applying manifests"
  kc apply -f "$TMP_DIR/rendered.yaml"

  local deployments d failed=""
  deployments=$(kc -n "$NAMESPACE" get deployments -l app.kubernetes.io/part-of=pitchbend-live \
    -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}')
  [[ -n "$deployments" ]] || die "no PitchBend Live Deployments found after apply"
  for d in $deployments; do
    log "Waiting for deployment/$d (timeout $ROLLOUT_TIMEOUT)"
    kc -n "$NAMESPACE" rollout status "deployment/$d" --timeout="$ROLLOUT_TIMEOUT" || failed+=" $d"
  done
  if [[ -n "$failed" ]]; then
    printf '\nRollout did not complete for:%s\n' "$failed" >&2
    printf 'Investigate with:\n  kubectl -n %s get pods\n  kubectl -n %s describe deployment <name>\n  kubectl -n %s logs deployment/<name> --all-containers\n' \
      "$NAMESPACE" "$NAMESPACE" "$NAMESPACE" >&2
    exit 1
  fi

  printf '\nDeployed %s. Verify (ARCHITECTURE.md §9 acceptance criteria):\n' "$sha"
  cat <<EOF
  kubectl -n $NAMESPACE get pods,certificate
  curl -I https://<PUBLIC_HOST>/
  curl https://<PUBLIC_HOST>/api/health
  curl -N https://<PUBLIC_HOST>/api/health/stream   # ticks must arrive ~1 s apart
EOF
}

main "$@"
